prefix vm_get_memory_info C func so it does not conflict with Prometheus one
Follow up on https://github.com/VictoriaMetrics/metrics/pull/107

Running tests on VM produced an error:

duplicate symbol '_get_memory_info' in:

/private/var/folders/ds/3kj5p3v17ll0hsyvq380ryvm0000gn/T/go-link-2626146643/000002.o

/private/var/folders/ds/3kj5p3v17ll0hsyvq380ryvm0000gn/T/go-link-2626146643/000015.o
ld: 1 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see
invocation)

ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset 1.820s